project:
  type: website
  output-dir: docs

website:
  title: "Your Name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
    
    tools:
      - icon: trash
        href: https://www.mountainproject.com/area/112001458/the-dump
      - icon: twitter
        href: https://x.com
      - icon: linkedin
        href: https://www.linkedin.com/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com
          - text: Report a Bug
            href: https://github.com  

format:
  html:
    theme: pulse  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true



